# -*- coding: utf-8 -*-
"""Prodigy_Infotech_DS_Task-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xr_ZpqjSDc5spN2xvV8brOa372rKgUUv

# Prodigy Infotech

Author: Aarti Wani

Data Science Intern

Task-01

Task: Create a bar chart or histogram to visualize the distribution of a categorical or continuous variable, such as the distribution of ages or genders in a population.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

data=pd.read_csv('/content/drive/MyDrive/heart_2020_cleaned.csv')

data.shape

data.head()

data.isna().sum()

data.info()

sns.countplot(x='Sex',hue='HeartDisease',palette='Spectral',data=data)
plt.xlabel('Gender')
plt.ylabel('Population')

sns.countplot(x='Smoking',palette='Spectral',data=data)
plt.xlabel('Smoking')
plt.ylabel('Population')

categorical=data.select_dtypes(include='object').columns
for i in categorical:
  sns.barplot(x=data[i],y='BMI',data=data)
  plt.show()

numerical=data.select_dtypes(include='float64').columns
for i in numerical:
  sns.histplot(x=data[i],data=data,bins=25,kde=True,color='orange')
  plt.show()